// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '609894615950',
    projectId: 'liveasyauthapp1',
    authDomain: 'liveasyauthapp1.firebaseapp.com',
    storageBucket: 'liveasyauthapp1.firebasestorage.app',
    measurementId: 'G-8LX4BXBG8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:609894615950:android:4887890dd47dec0a5bf2df',
    messagingSenderId: '609894615950',
    projectId: 'liveasyauthapp1',
    storageBucket: 'liveasyauthapp1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:609894615950:ios:e0fc429c00b248525bf2df',
    messagingSenderId: '609894615950',
    projectId: 'liveasyauthapp1',
    storageBucket: 'liveasyauthapp1.firebasestorage.app',
    iosBundleId: 'com.example.liveasyauthapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:609894615950:ios:e0fc429c00b248525bf2df',
    messagingSenderId: '609894615950',
    projectId: 'liveasyauthapp1',
    storageBucket: 'liveasyauthapp1.firebasestorage.app',
    iosBundleId: 'com.example.liveasyauthapp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:609894615950:web:66ce11187f1dc6d35bf2df',
    messagingSenderId: '609894615950',
    projectId: 'liveasyauthapp1',
    authDomain: 'liveasyauthapp1.firebaseapp.com',
    storageBucket: 'liveasyauthapp1.firebasestorage.app',
    measurementId: 'G-9S6S69R43J',
  );

}
