// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD48iRG7-sxNw0KqZ59G9pzsLNbhqpLe8',
    appId: '1:1015119387480:web:aa0a965e534b771f86232d',
    messagingSenderId: '1015119387480',
    projectId: 'healthsync1-aae29',
    authDomain: 'healthsync1-aae29.firebaseapp.com',
    storageBucket: 'healthsync1-aae29.firebasestorage.app',
    measurementId: 'G-H3S9XH4LLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgkRb5gsfwS7556XzIl-gq-vAmqjbkepM',
    appId: '1:1015119387480:android:aa8b1c7da8c7410186232d',
    messagingSenderId: '1015119387480',
    projectId: 'healthsync1-aae29',
    storageBucket: 'healthsync1-aae29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA0GeBH6er7buy9wLVVvEQMHt-JTW5WL4',
    appId: '1:1015119387480:ios:7814cbca2db192e786232d',
    messagingSenderId: '1015119387480',
    projectId: 'healthsync1-aae29',
    storageBucket: 'healthsync1-aae29.firebasestorage.app',
    iosBundleId: 'com.example.healthsync1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA0GeBH6er7buy9wLVVvEQMHt-JTW5WL4',
    appId: '1:1015119387480:ios:7814cbca2db192e786232d',
    messagingSenderId: '1015119387480',
    projectId: 'healthsync1-aae29',
    storageBucket: 'healthsync1-aae29.firebasestorage.app',
    iosBundleId: 'com.example.healthsync1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD48iRG7-sxNw0KqZ59G9pzsLNbhqpLe8',
    appId: '1:1015119387480:web:9978b00a09dac0cb86232d',
    messagingSenderId: '1015119387480',
    projectId: 'healthsync1-aae29',
    authDomain: 'healthsync1-aae29.firebaseapp.com',
    storageBucket: 'healthsync1-aae29.firebasestorage.app',
    measurementId: 'G-NXT4YY02K3',
  );
}
